BusinessManagement/views/admin.py
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
import csv
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        #try:
        file_name=file.filename.split('.')
        if file and secure_filename(file.filename) and file_name[1]=='csv':
        #if file and secure_filename(file.filename):
            companies = []
            employees = []
            company_query = """
            INSERT INTO IS601_MP2_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE address = %(address)s, city = %(city)s, country=%(country)s, state=%(state)s, zip=%(zip)s, website=%(website)s 
            """
            employee_query = """
            INSERT INTO IS601_MP2_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, last_name = %(last_name)s, email = %(email)s, company_id = (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
            for row in csv.DictReader(stream, delimiter=','):
                #print(row) #example
                # TODO importcsv-3 extract company data and append to company list as a dict only with company data

                # TODO importcsv-4 extract employee data and append to employee list as a dict only with employee data
            
                if row["company_name"] and row["address"] and row["city"] and row["state"] and row["zip"] and row["web"]:
                    companies.append({"name": row["company_name"], "address": row['address'], "city": row['city'],"country": row["country"], "state": row['state'], "zip": row['zip'], "website": row['web']})

                if row["first_name"] and row["last_name"] and row["email"] and row["company_name"]:
                    employees.append({"first_name": row["first_name"], "last_name": row["last_name"], "email": row['email'], "company_name": row["company_name"]})
    
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                    flash(f"{len(companies)} company records inserted","success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error in processing and inserting records in company table", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                #pass
                flash("No companies data was loaded, list is empty","info")
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    # TODO importcsv-7 display flash message about number of employees loaded
                    flash(f"{len(employees)} employee records inserted","success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error in processing and inserting records in employee table", "danger")
            else:
                # TODO importcsv-8 display flash message (info) that no companies were loaded
                #pass
                flash("No employees data were loaded, list is empty","info")
        else:
            flash("The file format is not correct, please import csv file", "danger")
    return render_template("upload.html")

BusinessManagement/views/company.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from sql.db import DB
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():
    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count for the company
    # don't do SELECT *
    query = """SELECT id, name, address, city, country, state,zip, website, (SELECT count(id) FROM IS601_MP2_Employees WHERE c.id=company_id GROUP BY company_id)
        as employees from IS601_MP2_Companies as c WHERE 1=1"""
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "city", "country", "state"]
    # TODO search-2 get name, country, state, column, order, limit request args
    name = request.args.get("name")
    country = request.args.get("country")
    state = request.args.get("state")
    column = request.args.get("column")
    order = request.args.get("order")
    limit = request.args.get("limit", 10)
    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND name like %s"
        args.append(f'%{name}%')
    # TODO search-4 append an equality filter for country if provided
    if country:
        query += " AND country = %s"
        args.append(f'{country}')
    # TODO search-5 append an equality filter for state if provided
    if state:
        query += " AND state = %s"
        args.append(f'{state}')
    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    if column and order:
        if column in ["name","city","country","state"] \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {column} {order}"
    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    if limit and int(limit) > 0 and int(limit) <= 100:
        # technically this should follow the same rules as col/order
        # but it seems to work with the placeholder mapping with
        # this connector
        query += " LIMIT %s"
        args.append(int(limit))
    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    
    print("query",query)
    print("args", args)
    try:
        resp = DB.selectAll(query, *args)
        if resp.status:
            rows = resp.rows
    except Exception as e:
        import traceback
        print(traceback.format_exc())
        # TODO search-9 make message user friendly
        flash("Sorry, data is not available", "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    return render_template("list_companies.html", resp=rows, allowed_columns=allowed_columns)

@company.route("/add", methods=["GET","POST"])
def add():
    if request.method == "POST":
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        # TODO add-2 name is required (flash proper error message)
        # TODO add-3 address is required (flash proper error message)
        # TODO add-4 city is required (flash proper error message)
        # TODO add-5 state is required (flash proper error message)
        # TODO add-6 country is required (flash proper error message)
        # TODO add-7 website is not required
        name = request.form.get("name")
        address = request.form.get("address")
        city = request.form.get("city")
        state = request.form.get("state")
        country = request.form.get("country")
        zipcode = request.form.get("zip")
        website = request.form.get("website", None)
        if name=="":
            flash("Please add name", "danger")
            return redirect(url_for("company.add"))
        if address=="":
            flash("Please add address", "danger")
            return redirect(url_for("company.add"))
        if city=="":
            flash("Please add city", "danger")
            return redirect(url_for("company.add"))
        if state=="":
            flash("Please add state", "danger")
            return redirect(url_for("company.add"))
        if country=="":
            flash("Please add Country", "danger")
            return redirect(url_for("company.add"))
        has_error = False # use this to control whether or not an insert occurs
        if not has_error:
            try:
                result = DB.insertOne("""INSERT INTO IS601_MP2_Companies (name, address,city,state,country,zip,website)
                VALUES(%s, %s, %s, %s, %s, %s, %s)"""
                ,name, address,city,state,country,zipcode,website) # <-- TODO add-8 add query and add arguments
                if result.status:
                    flash("Company has been added successfully", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                flash("Sorry, company's data cannot be added", "danger")       
    return render_template("add_company.html")

@company.route("/edit", methods=["GET", "POST"])
def edit():
    # TODO edit-1 request args id is required (flash proper error message)
    id = request.args.get("id")
    row = None
    if id is None:
        flash("ID is missing", "danger")
        return redirect(url_for("company.search"))
    else: # TODO update this for TODO edit-1

        #if request.method == "POST" and request.form.get("name") and request.form.get("address") and request.form.get("city") and \
            #request.form.get("state") and request.form.get("country"):
        if request.method == "POST":  
            # TODO edit-2 retrieve form data for name, address, city, state, country, zip, website
            # TODO edit-3 name is required (flash proper error message)
            # TODO edit-4 address is required (flash proper error message)
            # TODO edit-5 city is required (flash proper error message)
            # TODO edit-6 state is required (flash proper error message)
            # TODO edit-7 country is required (flash proper error message)
            # TODO edit-8 website is not required 
            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            #data = [name, address, city, state, country, zipcode, website]
            
            has_error=False
            name = request.form.get("name")
            address = request.form.get("address")
            city = request.form.get("city")
            state = request.form.get("state")
            country = request.form.get("country")
            zipcode = request.form.get("zip",None)
            website = request.form.get("website",None)
            print("Name",name)
            if name=="":
                flash("Name is missing", "danger")
                has_error=True
            if address=="":
                flash("Address is missing", "danger")
                has_error=True
            if city=="":
                flash("City is missing", "danger")
                has_error=True
            if state=="":
                flash("State is missing", "danger")
                has_error=True
            if country=="":
                flash("Country is missing", "danger")
                has_error=True
            data = [name, address, city, state, country, zipcode, website]
            data.append(id)
            try:
                # TODO edit-9 fill in proper update query
                if not has_error:
                    result = DB.update("UPDATE IS601_MP2_Companies SET name=%s, address=%s, city=%s, state=%s, country=%s, zip=%s, website= %s WHERE id = %s", *data)
                    if result.status:
                        flash("Updated record", "success")
            except Exception as e:
                # TODO edit-10 make this user-friendly
                flash("Data cannot be updated", "danger")
        try:
            # TODO edit-11 fetch the updated data
            result = DB.selectOne("SELECT name, address, city, state, country, zip, website FROM IS601_MP2_Companies WHERE id = %s", id)
            if result.status:
                row = result.row
                
        except Exception as e:
            # TODO edit-12 make this user-friendly
            flash("Data cannot be fetched", "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", row=row)

@company.route("/delete", methods=["GET"])
def delete():
    # TODO delete-1 delete company by id (unallocate any employees)
    # TODO delete-2 redirect to company search
    # TODO delete-3 pass all argument except id to this route
    # TODO delete-4 ensure a flash message shows for successful delete
    id = request.args.get("id")
    # make a mutable dict
    args = {**request.args}
    if id:
        try:
            query=DB.selectAll("SELECT company_id FROM IS601_MP2_Employees")
            if query.status: 
                rows=query.rows
            companyid_values=[]
            for row in rows:
                if row['company_id'] is not None:
                    companyid_values.append(int(row['company_id']))
            print(companyid_values)
            print(id)
            if int(id) in companyid_values:
                print("Yes")
                result_employee=DB.update("UPDATE IS601_MP2_Employees SET company_id=NULL WHERE company_id= %s",id)
                result = DB.delete("DELETE FROM IS601_MP2_Companies WHERE id = %s", id)
                if result.status and result_employee.status:
                    flash("Company data deleted", "success")
            else:
                print("No")
                result = DB.delete("DELETE FROM IS601_MP2_Companies WHERE id = %s", id)
                if result.status:
                    flash("Company data deleted", "success")
        except Exception as e:
            import traceback
            print(traceback.format_exc())

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Name</label>
                <input class="form-control" id="n" name="name" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="a">Address</label>
                <input class="form-control" id="a" name="address" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="c">City</label>
                <input class="form-control" id="c" name="city" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="w">Website</label>
                <input class="form-control" id="w" name="website" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="z">Zipcode</label>
                <input class="form-control" id="z" name="Zip" />
            </div>
            {#
            generate fields with proper types for
            name
            address
            city
            website
            #}
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="f">First Name</label>
                <input class="form-control" id="f" name="first_name" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="l">Last Name</label>
                <input class="form-control" id="l" name="last_name" />
            </div>
            <div class="form-group mb-4">
                <label class="form-label" for="e">Email</label>
                <input class="form-control" id="e" name="email" />
            </div>
            {#
            generate fields with proper types for
            first_name
            last_name
            email
            #}
            {# use the below for company selection #}
            {% include "company_dropdown.html" %}
            <input type="submit" class="btn btn-primary mt-5" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% set comps = get_companies() %}
{# can set val prior to inclusion to prefill this field #}
{# TODO DO NOT EDIT #}
<select class="form-select" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{request.args.get('country', '')}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{request.args.get('state', '')}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{request.args.get('country', '')}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{request.args.get('state', '')}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{request.args.get('state', '')}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{request.args.get('country', 'US')}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

BusinessManagement/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Ducks In a Row</div>
    <div class="w-50 mx-auto bg-light text-center caption border">At Ducks In A Row, we help
        organize your
        companies and
        employees all in one simple dashboard.</div>
    <div class="lead">Brought to you by Anisha (as4283) from section IS601-007
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace both with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - MP2</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                {# TODO replace my ucid mt85 with your ucid #}
                <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-as4283</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {# TODO fill in the relevant hrefs using url_for() #}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- company dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                            </ul>
                        </li>
                        <!-- employee dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Employee
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                            </ul>
                        </li>
                        <!-- admin dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-scroll" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2022.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    <form class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
            <label class="visually-hidden" for="name">Name</label>
            <input type="text" name="name" class="form-control" id="Name" placeholder="name"
                value="{{request.args.get('name') or ''}}">
        </div>
        <div class="col-12">
            <label class="visually-hidden" for="order">Order</label>
            <select class="form-select" id="order" name="order" value="{{request.args.get('order')}}">
                <option value="">Choose...</option>
                <option {{'selected' if request.args.get('order')=="asc" }} value="asc">+</option>
                <option {{'selected' if request.args.get('order')=="desc" }} value="desc">-</option>
            </select>
        </div>
        <div class="col-12">
            <label class="visually-hidden" for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    <form method="GET">
        {% with layout = "horizontal" %}
        {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = [] %}
        {% include "sort_filter.html" %}
        {% endwith %}
        
        <div class="col-12">
            <input type="submit" class="btn btn-primary mb-lg-0" value="Filter" />
        </div>
        <div class="col-12">
            <a href="?" class="btn btn-secondary">Reset</a>
        </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if resp and resp|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {% for r in resp[0] %}
                <th>{{r}}</th>
                {% endfor %}
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for r in resp %}
            <tr>
            {% for v in r.values() %}
                <td>{{v}}</td>
                {% endfor %}
                <td><a href="{{url_for('employee.search', company_id=r.get('id'), company_name=r.get('name'),**request.args)}}" class="btn btn-secondary btn-sm">View</a>
                    <a href="{{url_for('company.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                    {# **request.args spreads the key value pairs to be part of the url#}
                    {# the idea is to pass it to the next route #}
                    <a href="{{url_for('company.delete', id=r.get('id'), **request.args)}}"
                        class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argument
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}